[2013-12-06 02:40:38] log.ERROR: 500 - Class 'validators_connexion' not found @ /user/inscription
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'validators_connexion' not found' in D:\xampp\htdocs\azertea\app\controllers\UserController.php:33
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-12-06 02:41:46] log.ERROR: 500 - Class 'validators_user' not found @ /user/inscription
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'validators_user' not found' in D:\xampp\htdocs\azertea\app\controllers\UserController.php:33
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-12-06 02:42:18] log.ERROR: 500 - Class 'validators_user' not found @ /user/inscription
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'validators_user' not found' in D:\xampp\htdocs\azertea\app\controllers\UserController.php:33
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-12-06 02:42:55] log.ERROR: 500 - Class 'validators_user' not found @ /user/inscription
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'validators_user' not found' in D:\xampp\htdocs\azertea\app\controllers\UserController.php:33
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-12-06 02:44:27] log.ERROR: 500 - Class 'validators_user' not found @ /user/inscription
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'validators_user' not found' in D:\xampp\htdocs\azertea\app\controllers\UserController.php:33
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-12-06 02:44:47] log.ERROR: 500 - Class 'validators_user' not found @ /user/inscription
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'validators_user' not found' in D:\xampp\htdocs\azertea\app\controllers\UserController.php:33
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-12-06 02:45:52] log.ERROR: 500 - Class 'validators_user' not found @ /user/inscription
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'validators_user' not found' in D:\xampp\htdocs\azertea\app\controllers\UserController.php:33
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-12-06 02:49:45] log.ERROR: 500 - Class 'validators_user' not found @ /user/inscription
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'validators_user' not found' in D:\xampp\htdocs\azertea\app\controllers\UserController.php:33
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-12-06 02:50:40] log.ERROR: 500 - Class 'validators_user' not found @ /user/inscription
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'validators_user' not found' in D:\xampp\htdocs\azertea\app\controllers\UserController.php:33
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-12-06 02:53:06] log.ERROR: 500 - Call to undefined method Illuminate\Database\Query\Builder::isTakenUsername() @ /user/inscription
exception 'BadMethodCallException' with message 'Call to undefined method Illuminate\Database\Query\Builder::isTakenUsername()' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php:1658
Stack trace:
#0 [internal function]: Illuminate\Database\Query\Builder->__call('isTakenUsername', Array)
#1 [internal function]: Illuminate\Database\Query\Builder->isTakenUsername(NULL)
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array)
#3 [internal function]: Illuminate\Database\Eloquent\Builder->__call('isTakenUsername', Array)
#4 [internal function]: Illuminate\Database\Eloquent\Builder->isTakenUsername(NULL)
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(2653): call_user_func_array(Array, Array)
#6 [internal function]: Illuminate\Database\Eloquent\Model->__call('isTakenUsername', Array)
#7 [internal function]: User->isTakenUsername(NULL)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(2667): call_user_func_array(Array, Array)
#9 D:\xampp\htdocs\azertea\app\validators\validators_user.php(25): Illuminate\Database\Eloquent\Model::__callStatic('isTakenUsername', Array)
#10 D:\xampp\htdocs\azertea\app\validators\validators_user.php(25): User::isTakenUsername(NULL)
#11 [internal function]: validators_user->{closure}('username', 'username', Array, Object(Illuminate\Validation\Validator))
#12 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(1870): call_user_func_array(Object(Closure), Array)
#13 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(1905): Illuminate\Validation\Validator->callExtension('existing_nick', Array)
#14 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->__call('validateExistin...', Array)
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->validateExistingNick('username', 'username', Array, Object(Illuminate\Validation\Validator))
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(225): Illuminate\Validation\Validator->validate('username', 'existing_nick:n...')
#17 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(239): Illuminate\Validation\Validator->passes()
#18 D:\xampp\htdocs\azertea\app\validators\BaseValidator.php(11): Illuminate\Validation\Validator->fails()
#19 D:\xampp\htdocs\azertea\app\validators\validators_user.php(38): BaseValidator->test(Array)
#20 D:\xampp\htdocs\azertea\app\controllers\UserController.php(34): validators_user->register()
#21 [internal function]: UserController->postRegister()
#22 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#23 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postRegister', Array)
#24 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postRegister', Array)
#25 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#26 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#27 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#28 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#29 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#30 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#31 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#32 {main} [] []
[2013-12-06 02:53:41] log.ERROR: 500 - Call to undefined method Illuminate\Database\Query\Builder::isTakenUsername() @ /user/inscription
exception 'BadMethodCallException' with message 'Call to undefined method Illuminate\Database\Query\Builder::isTakenUsername()' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php:1658
Stack trace:
#0 [internal function]: Illuminate\Database\Query\Builder->__call('isTakenUsername', Array)
#1 [internal function]: Illuminate\Database\Query\Builder->isTakenUsername(NULL)
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array)
#3 [internal function]: Illuminate\Database\Eloquent\Builder->__call('isTakenUsername', Array)
#4 [internal function]: Illuminate\Database\Eloquent\Builder->isTakenUsername(NULL)
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(2653): call_user_func_array(Array, Array)
#6 [internal function]: Illuminate\Database\Eloquent\Model->__call('isTakenUsername', Array)
#7 [internal function]: User->isTakenUsername(NULL)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(2667): call_user_func_array(Array, Array)
#9 D:\xampp\htdocs\azertea\app\validators\validators_user.php(25): Illuminate\Database\Eloquent\Model::__callStatic('isTakenUsername', Array)
#10 D:\xampp\htdocs\azertea\app\validators\validators_user.php(25): User::isTakenUsername(NULL)
#11 [internal function]: validators_user->{closure}('username', 'username', Array, Object(Illuminate\Validation\Validator))
#12 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(1870): call_user_func_array(Object(Closure), Array)
#13 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(1905): Illuminate\Validation\Validator->callExtension('existing_nick', Array)
#14 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->__call('validateExistin...', Array)
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->validateExistingNick('username', 'username', Array, Object(Illuminate\Validation\Validator))
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(225): Illuminate\Validation\Validator->validate('username', 'existing_nick:n...')
#17 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(239): Illuminate\Validation\Validator->passes()
#18 D:\xampp\htdocs\azertea\app\validators\BaseValidator.php(11): Illuminate\Validation\Validator->fails()
#19 D:\xampp\htdocs\azertea\app\validators\validators_user.php(38): BaseValidator->test(Array)
#20 D:\xampp\htdocs\azertea\app\controllers\UserController.php(34): validators_user->register()
#21 [internal function]: UserController->postRegister()
#22 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#23 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postRegister', Array)
#24 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postRegister', Array)
#25 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#26 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#27 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#28 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#29 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#30 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#31 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#32 {main} [] []
[2013-12-06 02:54:05] log.ERROR: 500 - SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azertea.users' doesn't exist (SQL: select count(*) as aggregate from `users` where `username` is null) (Bindings: array (
)) @ /user/inscription
exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azertea.users' doesn't exist' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:272
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(272): PDO->prepare('select count(*)...')
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'select count(*)...', Array)
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(277): Illuminate\Database\Connection->run('select count(*)...', Array, Object(Closure))
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1028): Illuminate\Database\Connection->select('select count(*)...', Array)
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1018): Illuminate\Database\Query\Builder->runSelect()
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1005): Illuminate\Database\Query\Builder->getFresh(Array)
#6 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1369): Illuminate\Database\Query\Builder->get(Array)
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1311): Illuminate\Database\Query\Builder->aggregate('count', Array)
#8 [internal function]: Illuminate\Database\Query\Builder->count()
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array)
#10 D:\xampp\htdocs\azertea\app\models\User.php(52): Illuminate\Database\Eloquent\Builder->__call('count', Array)
#11 D:\xampp\htdocs\azertea\app\models\User.php(52): Illuminate\Database\Eloquent\Builder->count()
#12 D:\xampp\htdocs\azertea\app\validators\validators_user.php(25): User::isTakenUsername(NULL)
#13 [internal function]: validators_user->{closure}('username', 'username', Array, Object(Illuminate\Validation\Validator))
#14 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(1870): call_user_func_array(Object(Closure), Array)
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(1905): Illuminate\Validation\Validator->callExtension('existing_nick', Array)
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->__call('validateExistin...', Array)
#17 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->validateExistingNick('username', 'username', Array, Object(Illuminate\Validation\Validator))
#18 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(225): Illuminate\Validation\Validator->validate('username', 'existing_nick:n...')
#19 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(239): Illuminate\Validation\Validator->passes()
#20 D:\xampp\htdocs\azertea\app\validators\BaseValidator.php(11): Illuminate\Validation\Validator->fails()
#21 D:\xampp\htdocs\azertea\app\validators\validators_user.php(38): BaseValidator->test(Array)
#22 D:\xampp\htdocs\azertea\app\controllers\UserController.php(34): validators_user->register()
#23 [internal function]: UserController->postRegister()
#24 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#25 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postRegister', Array)
#26 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postRegister', Array)
#27 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#28 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#29 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#30 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#31 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#32 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#33 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#34 {main}

Next exception 'Exception' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azertea.users' doesn't exist (SQL: select count(*) as aggregate from `users` where `username` is null) (Bindings: array (
))' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'select count(*)...', Array)
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(277): Illuminate\Database\Connection->run('select count(*)...', Array, Object(Closure))
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1028): Illuminate\Database\Connection->select('select count(*)...', Array)
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1018): Illuminate\Database\Query\Builder->runSelect()
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1005): Illuminate\Database\Query\Builder->getFresh(Array)
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1369): Illuminate\Database\Query\Builder->get(Array)
#6 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1311): Illuminate\Database\Query\Builder->aggregate('count', Array)
#7 [internal function]: Illuminate\Database\Query\Builder->count()
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array)
#9 D:\xampp\htdocs\azertea\app\models\User.php(52): Illuminate\Database\Eloquent\Builder->__call('count', Array)
#10 D:\xampp\htdocs\azertea\app\models\User.php(52): Illuminate\Database\Eloquent\Builder->count()
#11 D:\xampp\htdocs\azertea\app\validators\validators_user.php(25): User::isTakenUsername(NULL)
#12 [internal function]: validators_user->{closure}('username', 'username', Array, Object(Illuminate\Validation\Validator))
#13 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(1870): call_user_func_array(Object(Closure), Array)
#14 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(1905): Illuminate\Validation\Validator->callExtension('existing_nick', Array)
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->__call('validateExistin...', Array)
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->validateExistingNick('username', 'username', Array, Object(Illuminate\Validation\Validator))
#17 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(225): Illuminate\Validation\Validator->validate('username', 'existing_nick:n...')
#18 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(239): Illuminate\Validation\Validator->passes()
#19 D:\xampp\htdocs\azertea\app\validators\BaseValidator.php(11): Illuminate\Validation\Validator->fails()
#20 D:\xampp\htdocs\azertea\app\validators\validators_user.php(38): BaseValidator->test(Array)
#21 D:\xampp\htdocs\azertea\app\controllers\UserController.php(34): validators_user->register()
#22 [internal function]: UserController->postRegister()
#23 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#24 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postRegister', Array)
#25 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postRegister', Array)
#26 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#27 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#28 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#29 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#30 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#31 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#32 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#33 {main} [] []
[2013-12-06 02:54:18] log.ERROR: 500 - SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azertea.user' doesn't exist (SQL: select count(*) as aggregate from `user` where `username` is null) (Bindings: array (
)) @ /user/inscription
exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azertea.user' doesn't exist' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:272
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(272): PDO->prepare('select count(*)...')
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'select count(*)...', Array)
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(277): Illuminate\Database\Connection->run('select count(*)...', Array, Object(Closure))
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1028): Illuminate\Database\Connection->select('select count(*)...', Array)
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1018): Illuminate\Database\Query\Builder->runSelect()
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1005): Illuminate\Database\Query\Builder->getFresh(Array)
#6 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1369): Illuminate\Database\Query\Builder->get(Array)
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1311): Illuminate\Database\Query\Builder->aggregate('count', Array)
#8 [internal function]: Illuminate\Database\Query\Builder->count()
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array)
#10 D:\xampp\htdocs\azertea\app\models\User.php(52): Illuminate\Database\Eloquent\Builder->__call('count', Array)
#11 D:\xampp\htdocs\azertea\app\models\User.php(52): Illuminate\Database\Eloquent\Builder->count()
#12 D:\xampp\htdocs\azertea\app\validators\validators_user.php(25): User::isTakenUsername(NULL)
#13 [internal function]: validators_user->{closure}('username', 'username', Array, Object(Illuminate\Validation\Validator))
#14 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(1870): call_user_func_array(Object(Closure), Array)
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(1905): Illuminate\Validation\Validator->callExtension('existing_nick', Array)
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->__call('validateExistin...', Array)
#17 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->validateExistingNick('username', 'username', Array, Object(Illuminate\Validation\Validator))
#18 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(225): Illuminate\Validation\Validator->validate('username', 'existing_nick:n...')
#19 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(239): Illuminate\Validation\Validator->passes()
#20 D:\xampp\htdocs\azertea\app\validators\BaseValidator.php(11): Illuminate\Validation\Validator->fails()
#21 D:\xampp\htdocs\azertea\app\validators\validators_user.php(38): BaseValidator->test(Array)
#22 D:\xampp\htdocs\azertea\app\controllers\UserController.php(34): validators_user->register()
#23 [internal function]: UserController->postRegister()
#24 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#25 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postRegister', Array)
#26 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postRegister', Array)
#27 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#28 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#29 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#30 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#31 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#32 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#33 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#34 {main}

Next exception 'Exception' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'azertea.user' doesn't exist (SQL: select count(*) as aggregate from `user` where `username` is null) (Bindings: array (
))' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'select count(*)...', Array)
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(277): Illuminate\Database\Connection->run('select count(*)...', Array, Object(Closure))
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1028): Illuminate\Database\Connection->select('select count(*)...', Array)
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1018): Illuminate\Database\Query\Builder->runSelect()
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1005): Illuminate\Database\Query\Builder->getFresh(Array)
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1369): Illuminate\Database\Query\Builder->get(Array)
#6 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1311): Illuminate\Database\Query\Builder->aggregate('count', Array)
#7 [internal function]: Illuminate\Database\Query\Builder->count()
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array)
#9 D:\xampp\htdocs\azertea\app\models\User.php(52): Illuminate\Database\Eloquent\Builder->__call('count', Array)
#10 D:\xampp\htdocs\azertea\app\models\User.php(52): Illuminate\Database\Eloquent\Builder->count()
#11 D:\xampp\htdocs\azertea\app\validators\validators_user.php(25): User::isTakenUsername(NULL)
#12 [internal function]: validators_user->{closure}('username', 'username', Array, Object(Illuminate\Validation\Validator))
#13 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(1870): call_user_func_array(Object(Closure), Array)
#14 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(1905): Illuminate\Validation\Validator->callExtension('existing_nick', Array)
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->__call('validateExistin...', Array)
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->validateExistingNick('username', 'username', Array, Object(Illuminate\Validation\Validator))
#17 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(225): Illuminate\Validation\Validator->validate('username', 'existing_nick:n...')
#18 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(239): Illuminate\Validation\Validator->passes()
#19 D:\xampp\htdocs\azertea\app\validators\BaseValidator.php(11): Illuminate\Validation\Validator->fails()
#20 D:\xampp\htdocs\azertea\app\validators\validators_user.php(38): BaseValidator->test(Array)
#21 D:\xampp\htdocs\azertea\app\controllers\UserController.php(34): validators_user->register()
#22 [internal function]: UserController->postRegister()
#23 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#24 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postRegister', Array)
#25 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postRegister', Array)
#26 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#27 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#28 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#29 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#30 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#31 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#32 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#33 {main} [] []
[2013-12-06 02:55:54] log.ERROR: 500 - SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'where clause' (SQL: select count(*) as aggregate from `utilisateur` where `username` is null) (Bindings: array (
)) @ /user/inscription
exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'where clause'' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:272
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(272): PDO->prepare('select count(*)...')
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'select count(*)...', Array)
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(277): Illuminate\Database\Connection->run('select count(*)...', Array, Object(Closure))
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1028): Illuminate\Database\Connection->select('select count(*)...', Array)
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1018): Illuminate\Database\Query\Builder->runSelect()
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1005): Illuminate\Database\Query\Builder->getFresh(Array)
#6 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1369): Illuminate\Database\Query\Builder->get(Array)
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1311): Illuminate\Database\Query\Builder->aggregate('count', Array)
#8 [internal function]: Illuminate\Database\Query\Builder->count()
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array)
#10 D:\xampp\htdocs\azertea\app\models\User.php(52): Illuminate\Database\Eloquent\Builder->__call('count', Array)
#11 D:\xampp\htdocs\azertea\app\models\User.php(52): Illuminate\Database\Eloquent\Builder->count()
#12 D:\xampp\htdocs\azertea\app\validators\validators_user.php(25): User::isTakenUsername(NULL)
#13 [internal function]: validators_user->{closure}('username', 'username', Array, Object(Illuminate\Validation\Validator))
#14 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(1870): call_user_func_array(Object(Closure), Array)
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(1905): Illuminate\Validation\Validator->callExtension('existing_nick', Array)
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->__call('validateExistin...', Array)
#17 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->validateExistingNick('username', 'username', Array, Object(Illuminate\Validation\Validator))
#18 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(225): Illuminate\Validation\Validator->validate('username', 'existing_nick:n...')
#19 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(239): Illuminate\Validation\Validator->passes()
#20 D:\xampp\htdocs\azertea\app\validators\BaseValidator.php(11): Illuminate\Validation\Validator->fails()
#21 D:\xampp\htdocs\azertea\app\validators\validators_user.php(38): BaseValidator->test(Array)
#22 D:\xampp\htdocs\azertea\app\controllers\UserController.php(34): validators_user->register()
#23 [internal function]: UserController->postRegister()
#24 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#25 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postRegister', Array)
#26 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postRegister', Array)
#27 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#28 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#29 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#30 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#31 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#32 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#33 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#34 {main}

Next exception 'Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'where clause' (SQL: select count(*) as aggregate from `utilisateur` where `username` is null) (Bindings: array (
))' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'select count(*)...', Array)
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(277): Illuminate\Database\Connection->run('select count(*)...', Array, Object(Closure))
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1028): Illuminate\Database\Connection->select('select count(*)...', Array)
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1018): Illuminate\Database\Query\Builder->runSelect()
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1005): Illuminate\Database\Query\Builder->getFresh(Array)
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1369): Illuminate\Database\Query\Builder->get(Array)
#6 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1311): Illuminate\Database\Query\Builder->aggregate('count', Array)
#7 [internal function]: Illuminate\Database\Query\Builder->count()
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array)
#9 D:\xampp\htdocs\azertea\app\models\User.php(52): Illuminate\Database\Eloquent\Builder->__call('count', Array)
#10 D:\xampp\htdocs\azertea\app\models\User.php(52): Illuminate\Database\Eloquent\Builder->count()
#11 D:\xampp\htdocs\azertea\app\validators\validators_user.php(25): User::isTakenUsername(NULL)
#12 [internal function]: validators_user->{closure}('username', 'username', Array, Object(Illuminate\Validation\Validator))
#13 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(1870): call_user_func_array(Object(Closure), Array)
#14 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(1905): Illuminate\Validation\Validator->callExtension('existing_nick', Array)
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->__call('validateExistin...', Array)
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->validateExistingNick('username', 'username', Array, Object(Illuminate\Validation\Validator))
#17 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(225): Illuminate\Validation\Validator->validate('username', 'existing_nick:n...')
#18 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(239): Illuminate\Validation\Validator->passes()
#19 D:\xampp\htdocs\azertea\app\validators\BaseValidator.php(11): Illuminate\Validation\Validator->fails()
#20 D:\xampp\htdocs\azertea\app\validators\validators_user.php(38): BaseValidator->test(Array)
#21 D:\xampp\htdocs\azertea\app\controllers\UserController.php(34): validators_user->register()
#22 [internal function]: UserController->postRegister()
#23 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#24 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postRegister', Array)
#25 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postRegister', Array)
#26 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#27 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#28 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#29 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#30 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#31 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#32 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#33 {main} [] []
[2013-12-06 02:58:29] log.ERROR: 500 - SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'field list' (SQL: insert into `utilisateur` (`email`, `username`, `password`, `updated_at`, `created_at`) values (?, ?, ?, ?, ?)) (Bindings: array (
  0 => 'l.mieulet@gmail.com',
  1 => 'username',
  2 => '$2y$08$7EcyW7LR3Gxs9uijmn3j8uNKCsF17owj9MMln/MjVTQ/eiz4DNk1m',
  3 => '2013-12-06 02:58:29',
  4 => '2013-12-06 02:58:29',
)) @ /user/inscription
exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'field list'' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:331
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(331): PDO->prepare('insert into `ut...')
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `ut...', Array)
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `ut...', Array, Object(Closure))
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `ut...', Array)
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(30): Illuminate\Database\Connection->insert('insert into `ut...', Array)
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1444): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `ut...', Array, 'id')
#6 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1259): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1259): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1229): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1140): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#12 D:\xampp\htdocs\azertea\app\controllers\UserController.php(40): Illuminate\Database\Eloquent\Model->save()
#13 [internal function]: UserController->postRegister()
#14 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postRegister', Array)
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postRegister', Array)
#17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#18 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#19 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#20 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#21 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#22 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#23 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#24 {main}

Next exception 'Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'field list' (SQL: insert into `utilisateur` (`email`, `username`, `password`, `updated_at`, `created_at`) values (?, ?, ?, ?, ?)) (Bindings: array (
  0 => 'l.mieulet@gmail.com',
  1 => 'username',
  2 => '$2y$08$7EcyW7LR3Gxs9uijmn3j8uNKCsF17owj9MMln/MjVTQ/eiz4DNk1m',
  3 => '2013-12-06 02:58:29',
  4 => '2013-12-06 02:58:29',
))' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'insert into `ut...', Array)
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `ut...', Array, Object(Closure))
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `ut...', Array)
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(30): Illuminate\Database\Connection->insert('insert into `ut...', Array)
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1444): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `ut...', Array, 'id')
#5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#6 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array)
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1259): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1259): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1229): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1140): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#11 D:\xampp\htdocs\azertea\app\controllers\UserController.php(40): Illuminate\Database\Eloquent\Model->save()
#12 [internal function]: UserController->postRegister()
#13 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#14 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postRegister', Array)
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postRegister', Array)
#16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#17 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#18 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#19 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#20 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#21 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#22 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#23 {main} [] []
[2013-12-06 02:58:57] log.ERROR: 500 - SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updated_at' in 'field list' (SQL: insert into `utilisateur` (`email`, `pseudo`, `mdp`, `updated_at`, `created_at`) values (?, ?, ?, ?, ?)) (Bindings: array (
  0 => 'l.mieulet@gmail.com',
  1 => 'username',
  2 => '$2y$08$xrEU5R.uzYd5hSarNFNvtu8kyjMXwDzNSd5vHyMNtsZPuS49r9RWi',
  3 => '2013-12-06 02:58:57',
  4 => '2013-12-06 02:58:57',
)) @ /user/inscription
exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updated_at' in 'field list'' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:331
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(331): PDO->prepare('insert into `ut...')
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `ut...', Array)
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `ut...', Array, Object(Closure))
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `ut...', Array)
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(30): Illuminate\Database\Connection->insert('insert into `ut...', Array)
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1444): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `ut...', Array, 'id')
#6 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1259): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1259): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1229): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1140): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#12 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1348): Illuminate\Database\Eloquent\Model->save()
#13 D:\xampp\htdocs\azertea\app\controllers\UserController.php(40): Illuminate\Database\Eloquent\Model->touch()
#14 [internal function]: UserController->postRegister()
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postRegister', Array)
#17 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postRegister', Array)
#18 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#19 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#20 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#21 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#22 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#23 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#24 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#25 {main}

Next exception 'Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updated_at' in 'field list' (SQL: insert into `utilisateur` (`email`, `pseudo`, `mdp`, `updated_at`, `created_at`) values (?, ?, ?, ?, ?)) (Bindings: array (
  0 => 'l.mieulet@gmail.com',
  1 => 'username',
  2 => '$2y$08$xrEU5R.uzYd5hSarNFNvtu8kyjMXwDzNSd5vHyMNtsZPuS49r9RWi',
  3 => '2013-12-06 02:58:57',
  4 => '2013-12-06 02:58:57',
))' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'insert into `ut...', Array)
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `ut...', Array, Object(Closure))
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `ut...', Array)
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(30): Illuminate\Database\Connection->insert('insert into `ut...', Array)
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1444): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `ut...', Array, 'id')
#5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#6 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array)
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1259): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1259): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1229): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1140): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1348): Illuminate\Database\Eloquent\Model->save()
#12 D:\xampp\htdocs\azertea\app\controllers\UserController.php(40): Illuminate\Database\Eloquent\Model->touch()
#13 [internal function]: UserController->postRegister()
#14 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postRegister', Array)
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postRegister', Array)
#17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#18 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#19 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#20 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#21 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#22 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#23 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#24 {main} [] []
[2013-12-06 02:59:06] log.ERROR: 500 - SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updated_at' in 'field list' (SQL: insert into `utilisateur` (`email`, `pseudo`, `mdp`, `updated_at`, `created_at`) values (?, ?, ?, ?, ?)) (Bindings: array (
  0 => 'l.mieulet@gmail.com',
  1 => 'username',
  2 => '$2y$08$7YW/vFJDLiStX6pbfXodCOfcjpEWxOna1IFYgzYkN0IDExzyHEwTS',
  3 => '2013-12-06 02:59:06',
  4 => '2013-12-06 02:59:06',
)) @ /user/inscription
exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updated_at' in 'field list'' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:331
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(331): PDO->prepare('insert into `ut...')
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `ut...', Array)
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `ut...', Array, Object(Closure))
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `ut...', Array)
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(30): Illuminate\Database\Connection->insert('insert into `ut...', Array)
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1444): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `ut...', Array, 'id')
#6 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1259): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1259): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1229): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1140): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#12 D:\xampp\htdocs\azertea\app\controllers\UserController.php(40): Illuminate\Database\Eloquent\Model->save()
#13 [internal function]: UserController->postRegister()
#14 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postRegister', Array)
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postRegister', Array)
#17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#18 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#19 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#20 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#21 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#22 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#23 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#24 {main}

Next exception 'Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updated_at' in 'field list' (SQL: insert into `utilisateur` (`email`, `pseudo`, `mdp`, `updated_at`, `created_at`) values (?, ?, ?, ?, ?)) (Bindings: array (
  0 => 'l.mieulet@gmail.com',
  1 => 'username',
  2 => '$2y$08$7YW/vFJDLiStX6pbfXodCOfcjpEWxOna1IFYgzYkN0IDExzyHEwTS',
  3 => '2013-12-06 02:59:06',
  4 => '2013-12-06 02:59:06',
))' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'insert into `ut...', Array)
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `ut...', Array, Object(Closure))
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `ut...', Array)
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(30): Illuminate\Database\Connection->insert('insert into `ut...', Array)
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1444): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `ut...', Array, 'id')
#5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#6 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array)
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1259): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1259): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1229): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1140): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#11 D:\xampp\htdocs\azertea\app\controllers\UserController.php(40): Illuminate\Database\Eloquent\Model->save()
#12 [internal function]: UserController->postRegister()
#13 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#14 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postRegister', Array)
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postRegister', Array)
#16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#17 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#18 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#19 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#20 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#21 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#22 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#23 {main} [] []
[2013-12-06 02:59:34] log.ERROR: 500 - Call to undefined method Illuminate\Database\Query\Builder::connexion() @ /user/inscription
exception 'BadMethodCallException' with message 'Call to undefined method Illuminate\Database\Query\Builder::connexion()' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php:1658
Stack trace:
#0 [internal function]: Illuminate\Database\Query\Builder->__call('connexion', Array)
#1 [internal function]: Illuminate\Database\Query\Builder->connexion(1)
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array)
#3 [internal function]: Illuminate\Database\Eloquent\Builder->__call('connexion', Array)
#4 [internal function]: Illuminate\Database\Eloquent\Builder->connexion(1)
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(2653): call_user_func_array(Array, Array)
#6 [internal function]: Illuminate\Database\Eloquent\Model->__call('connexion', Array)
#7 [internal function]: User->connexion(1)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(2667): call_user_func_array(Array, Array)
#9 D:\xampp\htdocs\azertea\app\controllers\UserController.php(42): Illuminate\Database\Eloquent\Model::__callStatic('connexion', Array)
#10 D:\xampp\htdocs\azertea\app\controllers\UserController.php(42): User::connexion(1)
#11 [internal function]: UserController->postRegister()
#12 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#13 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postRegister', Array)
#14 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postRegister', Array)
#15 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#17 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#18 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#19 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#20 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#21 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#22 {main} [] []
[2013-12-06 03:03:20] log.ERROR: 500 - SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'where clause' (SQL: select * from `utilisateur` where `username` = ? limit 1) (Bindings: array (
  0 => 'username',
)) @ /user/connect
exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'where clause'' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:272
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(272): PDO->prepare('select * from `...')
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'select * from `...', Array)
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(277): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1028): Illuminate\Database\Connection->select('select * from `...', Array)
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1018): Illuminate\Database\Query\Builder->runSelect()
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1005): Illuminate\Database\Query\Builder->getFresh(Array)
#6 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(441): Illuminate\Database\Query\Builder->get(Array)
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(132): Illuminate\Database\Eloquent\Builder->getModels(Array)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(108): Illuminate\Database\Eloquent\Builder->get(Array)
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Auth\EloquentUserProvider.php(63): Illuminate\Database\Eloquent\Builder->first()
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Auth\Guard.php(267): Illuminate\Auth\EloquentUserProvider->retrieveByCredentials(Array)
#11 [internal function]: Illuminate\Auth\Guard->attempt(Array)
#12 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Support\Manager.php(129): call_user_func_array(Array, Array)
#13 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(206): Illuminate\Support\Manager->__call('attempt', Array)
#14 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(206): Illuminate\Auth\AuthManager->attempt(Array)
#15 D:\xampp\htdocs\azertea\app\validators\validators_user.php(15): Illuminate\Support\Facades\Facade::__callStatic('attempt', Array)
#16 D:\xampp\htdocs\azertea\app\validators\validators_user.php(15): Illuminate\Support\Facades\Auth::attempt(Array)
#17 [internal function]: validators_user->{closure}('username', 'username', Array, Object(Illuminate\Validation\Validator))
#18 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(1870): call_user_func_array(Object(Closure), Array)
#19 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(1905): Illuminate\Validation\Validator->callExtension('connexion', Array)
#20 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->__call('validateConnexi...', Array)
#21 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->validateConnexion('username', 'username', Array, Object(Illuminate\Validation\Validator))
#22 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(225): Illuminate\Validation\Validator->validate('username', 'connexion')
#23 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(239): Illuminate\Validation\Validator->passes()
#24 D:\xampp\htdocs\azertea\app\validators\BaseValidator.php(11): Illuminate\Validation\Validator->fails()
#25 D:\xampp\htdocs\azertea\app\validators\validators_user.php(18): BaseValidator->test(Array)
#26 D:\xampp\htdocs\azertea\app\controllers\UserController.php(21): validators_user->login()
#27 [internal function]: UserController->postLogin()
#28 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#29 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postLogin', Array)
#30 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postLogin', Array)
#31 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#32 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#33 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#34 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#35 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#36 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#37 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#38 {main}

Next exception 'Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'where clause' (SQL: select * from `utilisateur` where `username` = ? limit 1) (Bindings: array (
  0 => 'username',
))' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'select * from `...', Array)
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(277): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1028): Illuminate\Database\Connection->select('select * from `...', Array)
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1018): Illuminate\Database\Query\Builder->runSelect()
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1005): Illuminate\Database\Query\Builder->getFresh(Array)
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(441): Illuminate\Database\Query\Builder->get(Array)
#6 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(132): Illuminate\Database\Eloquent\Builder->getModels(Array)
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(108): Illuminate\Database\Eloquent\Builder->get(Array)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Auth\EloquentUserProvider.php(63): Illuminate\Database\Eloquent\Builder->first()
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Auth\Guard.php(267): Illuminate\Auth\EloquentUserProvider->retrieveByCredentials(Array)
#10 [internal function]: Illuminate\Auth\Guard->attempt(Array)
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Support\Manager.php(129): call_user_func_array(Array, Array)
#12 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(206): Illuminate\Support\Manager->__call('attempt', Array)
#13 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(206): Illuminate\Auth\AuthManager->attempt(Array)
#14 D:\xampp\htdocs\azertea\app\validators\validators_user.php(15): Illuminate\Support\Facades\Facade::__callStatic('attempt', Array)
#15 D:\xampp\htdocs\azertea\app\validators\validators_user.php(15): Illuminate\Support\Facades\Auth::attempt(Array)
#16 [internal function]: validators_user->{closure}('username', 'username', Array, Object(Illuminate\Validation\Validator))
#17 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(1870): call_user_func_array(Object(Closure), Array)
#18 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(1905): Illuminate\Validation\Validator->callExtension('connexion', Array)
#19 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->__call('validateConnexi...', Array)
#20 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(264): Illuminate\Validation\Validator->validateConnexion('username', 'username', Array, Object(Illuminate\Validation\Validator))
#21 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(225): Illuminate\Validation\Validator->validate('username', 'connexion')
#22 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(239): Illuminate\Validation\Validator->passes()
#23 D:\xampp\htdocs\azertea\app\validators\BaseValidator.php(11): Illuminate\Validation\Validator->fails()
#24 D:\xampp\htdocs\azertea\app\validators\validators_user.php(18): BaseValidator->test(Array)
#25 D:\xampp\htdocs\azertea\app\controllers\UserController.php(21): validators_user->login()
#26 [internal function]: UserController->postLogin()
#27 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#28 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postLogin', Array)
#29 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postLogin', Array)
#30 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#31 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#32 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#33 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#34 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#35 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#36 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#37 {main} [] []
[2013-12-06 03:04:19] log.ERROR: 500 - Call to undefined method Illuminate\Database\Query\Builder::connexion() @ /user/connect
exception 'BadMethodCallException' with message 'Call to undefined method Illuminate\Database\Query\Builder::connexion()' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php:1658
Stack trace:
#0 [internal function]: Illuminate\Database\Query\Builder->__call('connexion', Array)
#1 [internal function]: Illuminate\Database\Query\Builder->connexion(1)
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array)
#3 [internal function]: Illuminate\Database\Eloquent\Builder->__call('connexion', Array)
#4 [internal function]: Illuminate\Database\Eloquent\Builder->connexion(1)
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(2653): call_user_func_array(Array, Array)
#6 [internal function]: Illuminate\Database\Eloquent\Model->__call('connexion', Array)
#7 [internal function]: User->connexion(1)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(2667): call_user_func_array(Array, Array)
#9 D:\xampp\htdocs\azertea\app\controllers\UserController.php(24): Illuminate\Database\Eloquent\Model::__callStatic('connexion', Array)
#10 D:\xampp\htdocs\azertea\app\controllers\UserController.php(24): User::connexion(1)
#11 [internal function]: UserController->postLogin()
#12 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#13 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postLogin', Array)
#14 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postLogin', Array)
#15 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#17 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#18 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#19 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#20 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#21 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#22 {main} [] []
[2013-12-06 03:08:56] log.ERROR: 500 - Class ProductController does not exist @ /annonce/add
exception 'ReflectionException' with message 'Class ProductController does not exist' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Container\Container.php:308
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Container\Container.php(308): ReflectionClass->__construct('ProductControll...')
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Container\Container.php(250): Illuminate\Container\Container->build('ProductControll...', Array)
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(480): Illuminate\Container\Container->make('ProductControll...', Array)
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(983): Illuminate\Foundation\Application->make('ProductControll...')
#4 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#6 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#10 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#11 {main} [] []
[2013-12-06 03:09:33] log.ERROR: 500 - syntax error, unexpected '$v' (T_VARIABLE), expecting function (T_FUNCTION) @ /annonce/add
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '$v' (T_VARIABLE), expecting function (T_FUNCTION)' in D:\xampp\htdocs\azertea\app\controllers\AnnonceController.php:20
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-12-06 03:10:43] log.ERROR: 404 - Controller method not found. @ /annonce/add
exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' with message 'Controller method not found.' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php:290
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(302): Illuminate\Routing\Controllers\Controller->missingMethod(Array)
#1 [internal function]: Illuminate\Routing\Controllers\Controller->__call('postProductAdd', Array)
#2 [internal function]: AnnonceController->postProductAdd()
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postProductAdd', Array)
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postProductAdd', Array)
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#13 {main} [] []
[2013-12-06 03:11:53] log.ERROR: 404 - Controller method not found. @ /annonce/add
exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' with message 'Controller method not found.' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php:290
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(302): Illuminate\Routing\Controllers\Controller->missingMethod(Array)
#1 [internal function]: Illuminate\Routing\Controllers\Controller->__call('postProductAdd', Array)
#2 [internal function]: AnnonceController->postProductAdd()
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postProductAdd', Array)
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postProductAdd', Array)
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#13 {main} [] []
[2013-12-06 03:12:16] log.ERROR: 500 - Class 'validators_add_annonce' not found @ /annonce/add
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'validators_add_annonce' not found' in D:\xampp\htdocs\azertea\app\controllers\AnnonceController.php:18
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-12-06 03:12:54] log.ERROR: 500 - Call to undefined method validators_add_annonce::login() @ /annonce/add
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method validators_add_annonce::login()' in D:\xampp\htdocs\azertea\app\controllers\AnnonceController.php:19
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-12-06 03:14:04] log.ERROR: 500 - Class 'Annonce' not found @ /annonce/add
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Annonce' not found' in D:\xampp\htdocs\azertea\app\controllers\AnnonceController.php:21
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-12-06 03:15:08] log.ERROR: 500 - SQLSTATE[42S22]: Column not found: 1054 Unknown column 'nomProduit' in 'field list' (SQL: insert into `annonce` (`nomProduit`, `description`, `prix`, `photo`, `url`, `dispo`, `updated_at`, `created_at`) values (?, ?, ?, ?, ?, ?, ?, ?)) (Bindings: array (
  0 => 'nom du produit',
  1 => 'description',
  2 => '11,2',
  3 => 'url de la photo',
  4 => 'url de vente',
  5 => false,
  6 => '2013-12-06 03:15:08',
  7 => '2013-12-06 03:15:08',
)) @ /annonce/add
exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'nomProduit' in 'field list'' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:331
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(331): PDO->prepare('insert into `an...')
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `an...', Array)
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `an...', Array, Object(Closure))
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `an...', Array)
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(30): Illuminate\Database\Connection->insert('insert into `an...', Array)
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1444): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `an...', Array, 'id')
#6 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1259): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1259): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1229): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1140): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#12 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1348): Illuminate\Database\Eloquent\Model->save()
#13 D:\xampp\htdocs\azertea\app\controllers\AnnonceController.php(28): Illuminate\Database\Eloquent\Model->touch()
#14 [internal function]: AnnonceController->postAnnonce()
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postAnnonce', Array)
#17 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postAnnonce', Array)
#18 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#19 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#20 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#21 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#22 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#23 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#24 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#25 {main}

Next exception 'Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'nomProduit' in 'field list' (SQL: insert into `annonce` (`nomProduit`, `description`, `prix`, `photo`, `url`, `dispo`, `updated_at`, `created_at`) values (?, ?, ?, ?, ?, ?, ?, ?)) (Bindings: array (
  0 => 'nom du produit',
  1 => 'description',
  2 => '11,2',
  3 => 'url de la photo',
  4 => 'url de vente',
  5 => false,
  6 => '2013-12-06 03:15:08',
  7 => '2013-12-06 03:15:08',
))' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'insert into `an...', Array)
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `an...', Array, Object(Closure))
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `an...', Array)
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(30): Illuminate\Database\Connection->insert('insert into `an...', Array)
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1444): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `an...', Array, 'id')
#5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#6 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array)
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1259): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1259): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1229): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1140): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1348): Illuminate\Database\Eloquent\Model->save()
#12 D:\xampp\htdocs\azertea\app\controllers\AnnonceController.php(28): Illuminate\Database\Eloquent\Model->touch()
#13 [internal function]: AnnonceController->postAnnonce()
#14 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postAnnonce', Array)
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postAnnonce', Array)
#17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#18 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#19 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#20 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#21 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#22 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#23 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#24 {main} [] []
[2013-12-06 03:15:43] log.ERROR: 500 - SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updated_at' in 'field list' (SQL: insert into `annonce` (`nom_produit`, `description`, `prix`, `photo`, `url`, `dispo`, `updated_at`, `created_at`) values (?, ?, ?, ?, ?, ?, ?, ?)) (Bindings: array (
  0 => 'nom du produit',
  1 => 'description',
  2 => '11,2',
  3 => 'url de la photo',
  4 => 'url de vente',
  5 => false,
  6 => '2013-12-06 03:15:43',
  7 => '2013-12-06 03:15:43',
)) @ /annonce/add
exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updated_at' in 'field list'' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:331
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(331): PDO->prepare('insert into `an...')
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(521): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `an...', Array)
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `an...', Array, Object(Closure))
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `an...', Array)
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(30): Illuminate\Database\Connection->insert('insert into `an...', Array)
#5 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1444): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `an...', Array, 'id')
#6 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1259): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1259): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1229): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1140): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#12 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1348): Illuminate\Database\Eloquent\Model->save()
#13 D:\xampp\htdocs\azertea\app\controllers\AnnonceController.php(28): Illuminate\Database\Eloquent\Model->touch()
#14 [internal function]: AnnonceController->postAnnonce()
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postAnnonce', Array)
#17 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postAnnonce', Array)
#18 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#19 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#20 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#21 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#22 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#23 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#24 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#25 {main}

Next exception 'Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updated_at' in 'field list' (SQL: insert into `annonce` (`nom_produit`, `description`, `prix`, `photo`, `url`, `dispo`, `updated_at`, `created_at`) values (?, ?, ?, ?, ?, ?, ?, ?)) (Bindings: array (
  0 => 'nom du produit',
  1 => 'description',
  2 => '11,2',
  3 => 'url de la photo',
  4 => 'url de vente',
  5 => false,
  6 => '2013-12-06 03:15:43',
  7 => '2013-12-06 03:15:43',
))' in D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php:556
Stack trace:
#0 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(529): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'insert into `an...', Array)
#1 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(332): Illuminate\Database\Connection->run('insert into `an...', Array, Object(Closure))
#2 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Connection.php(289): Illuminate\Database\Connection->statement('insert into `an...', Array)
#3 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(30): Illuminate\Database\Connection->insert('insert into `an...', Array)
#4 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1444): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `an...', Array, 'id')
#5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#6 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(786): call_user_func_array(Array, Array)
#7 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1259): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#8 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1259): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#9 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1229): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#10 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1140): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#11 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1348): Illuminate\Database\Eloquent\Model->save()
#12 D:\xampp\htdocs\azertea\app\controllers\AnnonceController.php(28): Illuminate\Database\Eloquent\Model->touch()
#13 [internal function]: AnnonceController->postAnnonce()
#14 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#15 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postAnnonce', Array)
#16 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postAnnonce', Array)
#17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#18 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array)
#19 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable()
#20 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#21 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#22 D:\xampp\htdocs\azertea\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#23 D:\xampp\htdocs\azertea\public\index.php(49): Illuminate\Foundation\Application->run()
#24 {main} [] []
[2013-12-06 04:37:08] log.ERROR: 405 - Exception @ /search
exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in /Users/benoit/Dev/L3/Nuit2013/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1439
Stack trace:
#0 /Users/benoit/Dev/L3/Nuit2013/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException))
#1 /Users/benoit/Dev/L3/Nuit2013/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /Users/benoit/Dev/L3/Nuit2013/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 /Users/benoit/Dev/L3/Nuit2013/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 /Users/benoit/Dev/L3/Nuit2013/public/index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-12-06 04:40:05] log.ERROR: 405 - Exception @ /search
exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in /Users/benoit/Dev/L3/Nuit2013/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1439
Stack trace:
#0 /Users/benoit/Dev/L3/Nuit2013/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException))
#1 /Users/benoit/Dev/L3/Nuit2013/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /Users/benoit/Dev/L3/Nuit2013/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 /Users/benoit/Dev/L3/Nuit2013/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 /Users/benoit/Dev/L3/Nuit2013/public/index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-12-06 04:48:39] log.ERROR: 404 - Exception @ /css/bootstrap.min.css
exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /Users/benoit/Dev/L3/Nuit2013/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429
Stack trace:
#0 /Users/benoit/Dev/L3/Nuit2013/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 /Users/benoit/Dev/L3/Nuit2013/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /Users/benoit/Dev/L3/Nuit2013/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 /Users/benoit/Dev/L3/Nuit2013/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 /Users/benoit/Dev/L3/Nuit2013/public/index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
